# Generated by Django 5.1.1 on 2024-12-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
